// routeTree.gen.ts is generated by the tanstackStart() vite plugin on `dev`/`build`
// (there is no standalone generator command); run a build/dev before `pnpm typecheck`.
import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
  })

  return router
}
