import { beforeAll, describe, expect, it } from 'vitest'
import { mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadRegistry } from '../src/registry.js'
import { resolve } from '../src/resolve.js'
import { emptyLock } from '../src/lockfile.js'
import { planComposedFiles } from '../src/plan/tier-composed.js'
import type { Graph, ResolvedBrick } from '../src/types.js'

const fixture = fileURLToPath(new URL('./fixtures/registry-basic', import.meta.url))
let graph: Graph

beforeAll(async () => {
  const reg = await loadRegistry(fixture)
  const r = resolve({ bricks: { alpha: {} }, overrides: {} }, reg)
  if (!r.ok) throw new Error('fixture must resolve')
  graph = r.graph
})

describe('planComposedFiles', () => {
  it('emits one compose op per composed target with a banner', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const ops = await planComposedFiles(graph, { projectDir: dir, lock: emptyLock(), overrides: {} })
    expect(ops).toHaveLength(1)
    expect(ops[0]).toMatchObject({ kind: 'compose', path: 'ops/compose.yml', contributors: ['alpha'] })
    expect((ops[0] as { contents: string }).contents).toContain('Generated by stacky')
    expect((ops[0] as { contents: string }).contents).toContain('alpha:')
  })

  it('applies stack.toml overrides after all fragments', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const ops = await planComposedFiles(graph, {
      projectDir: dir,
      lock: emptyLock(),
      overrides: { 'ops/compose.yml': { services: { alpha: { image: 'node:24' } } } },
    })
    expect((ops[0] as { contents: string }).contents).toContain('node:24')
    expect((ops[0] as { contents: string }).contents).not.toContain('node:22')
  })

  it('emits delete for a composed file no brick contributes to any more', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const lock = {
      ...emptyLock(),
      files: [{ path: 'ops/gone.yml', owner: '@composed' as const, tier: 'composed' as const, hash: 'h' }],
    }
    const ops = await planComposedFiles(graph, { projectDir: dir, lock, overrides: {} })
    expect(ops).toContainEqual({ kind: 'delete', path: 'ops/gone.yml', owner: '@composed' })
  })

  it('rejects a composed target where bricks disagree on merge strategy', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const bricksDir = await mkdtemp(join(tmpdir(), 'stacky-t2-bricks-'))
    await writeFile(join(bricksDir, 'a.yaml'), 'services:\n  a:\n    image: a\n', 'utf8')
    await writeFile(join(bricksDir, 'b.env'), 'FOO=1\n', 'utf8')

    const mkBrick = (name: string, strategy: 'yaml' | 'lines', from: string): ResolvedBrick => ({
      brick: {
        name,
        slot: name,
        summary: '',
        dir: bricksDir,
        requires: {},
        provides: [],
        params: {},
        files: [],
        fragments: [{ target: 'ops/mixed.yml', from, strategy }],
        inject: [],
      },
      params: {},
      inferred: false,
    })

    const mismatchedGraph: Graph = {
      bricks: [mkBrick('alpha2', 'yaml', 'a.yaml'), mkBrick('beta2', 'lines', 'b.env')],
    }

    await expect(
      planComposedFiles(mismatchedGraph, { projectDir: dir, lock: emptyLock(), overrides: {} }),
    ).rejects.toThrow(/ops\/mixed\.yml/)
  })
})

describe('planComposedFiles — json strategy', () => {
  it('deep-merges json fragments and applies a json override', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-json-'))
    const bricksDir = await mkdtemp(join(tmpdir(), 'stacky-json-bricks-'))
    await writeFile(join(bricksDir, 'a.json'), JSON.stringify({ scripts: { dev: 'vite' } }), 'utf8')
    await writeFile(join(bricksDir, 'b.json'), JSON.stringify({ scripts: { build: 'vite build' } }), 'utf8')

    const mk = (name: string, from: string): ResolvedBrick => ({
      brick: {
        name, slot: name, summary: '', dir: bricksDir, requires: {}, provides: [],
        params: {}, files: [], fragments: [{ target: 'app/package.json', from, strategy: 'json' }], inject: [],
      },
      params: {}, inferred: false,
    })
    const g: Graph = { bricks: [mk('a', 'a.json'), mk('b', 'b.json')] }

    const ops = await planComposedFiles(g, {
      projectDir: dir, lock: emptyLock(),
      overrides: { 'app/package.json': { scripts: { dev: 'vite dev --host' } } },
    })
    const contents = (ops[0] as { contents: string }).contents
    const parsed = JSON.parse(contents)
    expect(parsed.scripts).toEqual({ build: 'vite build', dev: 'vite dev --host' })
    expect(parsed['//']).toContain('Generated by stacky')
  })
})
