import { beforeAll, describe, expect, it } from 'vitest'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadRegistry } from '../src/registry.js'
import { resolve } from '../src/resolve.js'
import { emptyLock } from '../src/lockfile.js'
import { planComposedFiles } from '../src/plan/tier-composed.js'
import type { Graph } from '../src/types.js'

const fixture = fileURLToPath(new URL('./fixtures/registry-basic', import.meta.url))
let graph: Graph

beforeAll(async () => {
  const reg = await loadRegistry(fixture)
  const r = resolve({ bricks: { alpha: {} }, overrides: {} }, reg)
  if (!r.ok) throw new Error('fixture must resolve')
  graph = r.graph
})

describe('planComposedFiles', () => {
  it('emits one compose op per composed target with a banner', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const ops = await planComposedFiles(graph, { projectDir: dir, lock: emptyLock(), overrides: {} })
    expect(ops).toHaveLength(1)
    expect(ops[0]).toMatchObject({ kind: 'compose', path: 'ops/compose.yml', contributors: ['alpha'] })
    expect((ops[0] as { contents: string }).contents).toContain('Generated by stacky')
    expect((ops[0] as { contents: string }).contents).toContain('alpha:')
  })

  it('applies stack.toml overrides after all fragments', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const ops = await planComposedFiles(graph, {
      projectDir: dir,
      lock: emptyLock(),
      overrides: { 'ops/compose.yml': { services: { alpha: { image: 'node:24' } } } },
    })
    expect((ops[0] as { contents: string }).contents).toContain('node:24')
    expect((ops[0] as { contents: string }).contents).not.toContain('node:22')
  })

  it('emits delete for a composed file no brick contributes to any more', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stacky-t2-'))
    const lock = {
      ...emptyLock(),
      files: [{ path: 'ops/gone.yml', owner: '@composed' as const, tier: 'composed' as const, hash: 'h' }],
    }
    const ops = await planComposedFiles(graph, { projectDir: dir, lock, overrides: {} })
    expect(ops).toContainEqual({ kind: 'delete', path: 'ops/gone.yml', owner: '@composed' })
  })
})
