export type * from './types.js'
export { loadRegistry } from './registry.js'
export { emptyManifest, readManifest, writeManifest } from './manifest.js'
export { resolve } from './resolve.js'
export { exitCodeFor, formatError } from './errors.js'
export { emptyLock, fileState, hashContents, readLock, writeLock } from './lockfile.js'
export { renderTemplate } from './template.js'
export { deepMerge, mergeJson, mergeLines, mergeYaml, stringifyJson } from './merge.js'
export { hasConflicts, plan } from './plan/index.js'
export type { PlanContext } from './plan/index.js'
export { applyMarker, stripMarker } from './plan/tier-inject.js'
export { apply } from './apply.js'
