import { parse as parseYaml, stringify as stringifyYaml } from 'yaml'

export const BANNER_YAML = [
  '# Generated by stacky. Do not edit — changes are overwritten on `stacky apply`.',
  '# To customise, add an [overrides."<path>"] block to stack.toml.',
  '',
].join('\n')

export const BANNER_LINES = [
  '# Generated by stacky. Do not edit — changes are overwritten on `stacky apply`.',
  '',
].join('\n')

export const BANNER_JSON =
  'Generated by stacky — edit deviations via a stack.toml override; regenerated on `stacky apply`.'

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

/** Right-hand side wins on scalars and arrays; objects merge recursively. */
export function deepMerge<T>(a: T, b: unknown): T {
  if (!isPlainObject(a) || !isPlainObject(b)) return b as T
  const out: Record<string, unknown> = { ...a }
  for (const [key, value] of Object.entries(b)) {
    out[key] = key in out ? deepMerge(out[key], value) : value
  }
  return out as T
}

function sortKeys(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortKeys)
  if (isPlainObject(v)) {
    const out: Record<string, unknown> = {}
    for (const k of Object.keys(v).sort()) out[k] = sortKeys(v[k])
    return out
  }
  return v
}

/** Recursively key-sorted JSON, 2-space indent, trailing newline. */
export function stringifyJson(value: unknown): string {
  return `${JSON.stringify(sortKeys(value), null, 2)}\n`
}

/** Merges JSON fragments in order; keys sorted for byte-stability. */
export function mergeJson(fragments: string[]): string {
  let acc: Record<string, unknown> = {}
  for (const frag of fragments) {
    const parsed = JSON.parse(frag) as unknown
    if (isPlainObject(parsed)) acc = deepMerge(acc, parsed)
  }
  return stringifyJson({ '//': BANNER_JSON, ...acc })
}

/** Merges YAML fragments in the order given. Keys are sorted for byte-stability. */
export function mergeYaml(fragments: string[]): string {
  let acc: Record<string, unknown> = {}
  for (const frag of fragments) {
    const parsed = parseYaml(frag) as unknown
    if (parsed != null) acc = deepMerge(acc, parsed)
  }
  return BANNER_YAML + stringifyYaml(acc, { sortMapEntries: true })
}

/** Merges line-oriented fragments (.env.example, .gitignore) with per-brick headers. */
export function mergeLines(fragments: { brick: string; text: string }[]): string {
  const seen = new Set<string>()
  const blocks: string[] = []

  for (const { brick, text } of fragments) {
    const lines = text
      .split('\n')
      .map((l) => l.trimEnd())
      .filter((l) => l.length > 0 && !seen.has(l))
    for (const l of lines) seen.add(l)
    if (lines.length > 0) blocks.push(`# ${brick}\n${lines.join('\n')}`)
  }

  return `${BANNER_LINES}${blocks.join('\n\n')}\n`
}
